# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: format
        name: format
        description: Format code for Go.
        entry: golines ./ -m 120 -w --base-formatter gofmt --no-reformat-tags && gofumpt -l -w .
        types: [go]
        language: golang
        pass_filenames: false
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: golangci-lint run
        types: [go]
        language: golang
        pass_filenames: false
