{{- if .Values.apigwregister.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-apigw-register-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 600
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: apigw-register
          image: {{ default .Values.global.imageRegistry .Values.image.registry }}/{{ .Values.apigwregister.image.repository }}:v{{ default .Values.image.tag .Values.apigwregister.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          command: ["/data/bin/sync-apigateway.sh"]
          env:
            - name: BK_APIGW_NAME
              value: {{ .Values.apigwregister.apigwName }}
            - name: BK_API_URL_TMPL
              value: {{ .Values.apigwregister.bkApiUrlTmpl | required ".Values.apigwregister.bkApiUrlTmpl is required" }}
            - name: BK_APP_CODE
              value: {{ .Values.appCode }}
            - name: BK_APP_SECRET
              value: {{ .Values.appSecret }}
            - name: BK_APP_TENANT_ID
              value: {{ .Values.tenant.enabled | ternary "system" "default" | quote }}
            - name: BK_HCM_STAGE_NAME
              value: {{ .Values.apigwregister.stageName }}
            {{- if .Values.ingress.shareDomainEnable }}
            - name: BK_HCM_HOST
              value: {{ printf "%s://%s" .Values.global.bkDomainScheme .Values.ingress.host }}
            - name: BK_HCM_API_URL_PATH_PREFIX
              value: "apigw/"
            {{- else}}
            - name: BK_HCM_HOST
              value: {{ printf "%s://%s" .Values.global.bkDomainScheme .Values.ingress.apiserver.host }}
            - name: BK_HCM_API_URL_PATH_PREFIX
              value: ""
            {{- end }}
            - name: BK_HCM_MAINTAINER
              value: "{{ .Values.apigwregister.maintainer }}"
          resources: {{ toYaml .Values.apigwregister.resources | nindent 12 }}
{{- end }}
